config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' } #, confirmations: 'confirmations' }
  resources :users
  root to: "games#index"
  resources :games, only: [:index, :show, :new, :edit, :update, :destroy] do
    resources :characters
  end
  resources :photos, only: [:destroy]
  resources :cover_photos, only: [:destroy]
  resources :testimonials, only: [:destroy]
  resources :charges
  resources :orders
  resources :countdowns, only: [:create, :show, :index]
  get 'countdowns/:id/search' => 'countdowns#search', as: "search_path"
  get 'countdowns/:id/ending' => 'countdowns#ending', as: "ending_path"
  post 'games/:game_id/characters/invite' => 'characters#invite', as: "invite_path"
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :orders
  has_many :characters, through: :orders
  has_many :games, through: :orders

  def set_default_role
    self.role ||= :user
  end

  def full_name
    first_name + " " + last_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  before_invitation_created :email_admins
  after_invitation_accepted :email_invited_by

  def email_admins
    # example of before invitation created callback
  end

  def email_invited_by
    # example of after invitation accepted callback
  end

  def invitation_accepted?
    # or maybe just call valid? ??
    # or try invited_to_sign_up?
    created_by_invite? && User.invitation_accepted.include?(self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @orders = @user.orders.where(complete:true)
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      if params[:role]
        admin_only
        redirect_to users_path, :notice => "User updated."
      else
        redirect_to user_path(@user), :notice => "User updated."
      end
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role, :first_name, :last_name, :email)
  end

end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/edit.html.erb
<h3>Edit My Account Information</h3>

<p>Name: <%= @user.full_name if @user.first_name %></p>
<p>Email: <%= @user.email if @user.email %></p>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Change My password", edit_user_registration_path %>
<%= link_to "Back", :back %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>My Account</h3>
<div class="w3-center w3-card">
  <p>Name: <%= @user.full_name if @user.first_name %></p>
  <p>Email: <%= @user.email if @user.email %></p>
  <% if current_user.admin? %>
    <%= link_to "Manage Users", users_path, class: "w3-grey w3-center w3-button" %>
    <p></p>
    <!-- backup countdown button for admins only -->
    <% if PurchasedGame.first.present? %>
      <%= button_to("Begin Countdown", countdowns_path, params: {purchased_game_id: PurchasedGame.first.id}, class: "w3-grey w3-center w3-button" ) %>
    <% end %>
  <% end %><br>
  <%= link_to "Update My Account Information", edit_user_path(current_user) %>
  <br>
  <%= link_to "Change My password", edit_user_registration_path %>
</div>
<div>
  <ul>
  <% @orders.each do |order| %>
    <div class="w3-card">
      <p>Total amount: <%= number_to_currency(order.total/100) %></p>
      <% if order.purchased_at %>
        <p>Purchase date: <time datetime="<%= order.purchased_at %>" class="local_time"></time></p>
      <% end %>
      <ul>
        <% order.games.each do |game| %>
          <p><%= link_to game.title, game_path(game) %></p>
          <p><%= link_to "Assign Characters", game_characters_path(game) %></p>
          <% if game.countdown? %>
            <%= button_to("Begin Countdown", countdowns_path, params: {purchased_game_id: PurchasedGame.where(game: game, order: order).first.id}, class: "w3-grey w3-center w3-button" ) %>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
  </ul>
</div>