config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' } #, confirmations: 'confirmations' }
  resources :users
  root to: "games#index"
  resources :games, only: [:index, :show, :new, :edit, :update, :destroy] do
    resources :characters
  end
  resources :photos, only: [:destroy]
  resources :cover_photos, only: [:destroy]
  resources :testimonials, only: [:destroy]
  resources :charges
  resources :orders
  resources :countdowns, only: [:create, :show, :index]
  get 'countdowns/:id/search' => 'countdowns#search', as: "search_path"
  get 'countdowns/:id/ending' => 'countdowns#ending', as: "ending_path"
  post 'games/:game_id/characters/invite' => 'characters#invite', as: "invite_path"
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :testimonials, dependent: :nullify
  has_many :photos
  has_many :characters
  has_one  :cover_photo, dependent: :nullify

  accepts_nested_attributes_for :testimonials, allow_destroy: true, reject_if: lambda { |a| a[:description].blank? } # this prevents empty testimonials from getting saved

  accepts_nested_attributes_for :characters, allow_destroy: true, reject_if: lambda { |a| a[:player_packet].blank? && a[:name].blank? } # this prevents empty characters from getting saved

  has_attached_file :packet, default_url: "nil"
  validates_attachment_content_type :packet, :content_type => ["application/zip", "application/x-zip", "application/x-zip-compressed"]

  before_post_process :skip_for_zip

  scope :active, -> { where.not(packet_file_name: nil) }
  scope :coming_soon, -> { where(packet_file_name: nil) }

  def has_packet?
     packet.url != "nil"
  end

  def countdown?
    title == "Cuban Missile Crisis: Again!"
  end

  private

  def skip_for_zip
     ! %w(application/zip application/x-zip application/x-zip-compressed).include?(packet_content_type)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_only, except: [:index, :show]

  def index
    @user = current_user || User.new
  end

  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
    @game.testimonials.build
    @game.characters.build
  end

  def update
    @game = Game.find( params[:id] )
    @game.update( game_params )
    @game.packet = params[:game][:packet] if params[:game][:packet]
    params[:game][:images].each { |image| @game.photos.create(img: image) } if params[:game][:images]
    if params[:game][:cover_photo]
      @game.cover_photo.destroy if @game.cover_photo
      CoverPhoto.create(img: params[:game][:cover_photo], game: @game)
    end
    @game.save
    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find( params[:id] )
    @game.destroy
    redirect_to root_path
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def game_params
    params.require(:game).permit(:images, :title, :teaser, :included, :not_included, :difficulty, :price, :notes, :packet, {:testimonials_attributes => [:description, :id]}, characters_attributes: [:player_packet, :_destroy, :id, :name])
  end
end

app/views/games/_character_fields.html.erb
<p>
  <%= ff.label :name %>
  <%= ff.text_field :name %>
 </p>
 <p>
  <%= ff.label :update_player_packet %>
  <%= ff.file_field :player_packet %>
</p>
<p>----------------------------------------------</p>

app/views/games/_testimonial_fields.html.erb
<p>
  <%= ff.text_area :description, rows: 10 %>
</p>

app/views/games/edit.html.erb
<h1><%= @game.title %></h1>
<p><%= link_to "Delete Game", game_path(@game), method: "DELETE", :data => {:confirm => 'Are you sure you want to delete this game? This cannot be undone.'} %></p>
<div>
  <%= form_for @game, url: game_path, html: { multipart: true } do |form| %>
    <div>
      <h2>Title:</h2>
      <%= form.text_area :title %>
    </div>
    <div>
      <h2>Teaser:</h2>
      <%= form.text_area :teaser %>
    </div>
    <div>
      <h2>Included:</h2>
      <%= form.text_area :included %>
    </div>
    <div>
      <h2>Not included:</h2>
      <%= form.text_area :not_included %>
    </div>
    <div>
      <h2>Host Difficulty:</h2>
      <%= form.select :difficulty, options_for_select([ "Easy", "Medium", "Difficult", "Very Difficult" ], @game.difficulty) %>
    </div>
    <div>
      <h2>Host Notes:</h2>
      <%= form.text_area :notes %>
    </div>
    <div>
      <h2>Price (in cents):</h2>
      <%= form.text_field :price %>
    </div>
    <% if @game.cover_photo %>
      <h2>Change Cover Photo:</h2>
      <div>
        <%= image_tag(@game.cover_photo.img.url(:medium), id: @game.cover_photo.id) %>
        <p><%= form.file_field :cover_photo %></p>
        <%= link_to "Delete Cover Photo", cover_photo_path(@game.cover_photo), method: "DELETE", :data => {:confirm => 'Are you sure you want to delete this photo?'} %>

      </div>
    <% else %>
      <h2>Add Cover Photo:</h2>
      <div>
        <%= form.file_field :cover_photo %>
      </div>
    <% end %>
    <div>
      <h2>Add Photos:</h2>
      <%= form.file_field :images, multiple: true %>
    </div>
    <% if @game.photos.count > 0 %>
      <div>
        <h2>Delete Photos:</h2>
        <% @game.photos.each do |photo| %>
          <%= image_tag(photo.img.url(:medium), id: photo.id) %>
          <%= link_to "Delete", photo_path(photo), method: "DELETE", :data => {:confirm => 'Are you sure you want to delete this photo?'} %>
        <% end %>
      </div>
    <% end %>
    <div>
      <h2>Testimonials:</h2>
      <p>Use the box below to add a new testimonial.  Just one at a time for now.  An empty box will not create a new testimonial.</p>
      <% @game.testimonials.select {|t| t.id == nil}.each do |testimonial| %>
        <%= form.fields_for :testimonials, testimonial do |ff| %>
          <%= render "testimonial_fields", ff: ff %>
        <% end %>
      <% end %>

      <p>Use the box(es) below to edit or delete existing testimonials.</p>
      <% @game.testimonials.order(created_at: :desc).each do |testimonial| %>
        <%= form.fields_for :testimonials, testimonial do |ff| %>
          <%= render "testimonial_fields", ff: ff %>
          <%= link_to "Delete Testimonial", testimonial_path(testimonial), method: "DELETE", :data => {:confirm => 'Are you sure you want to delete this testimonial?'} %>
        <% end %>
      <% end %>

    </div>

    <h2>Host Packet:</h2>
    <% if @game.has_packet? %>
      <p><%=@game.packet%></p>
      <%= link_to("Download", @game.packet.url) %>
    <% end %>
    <div>
      <%= form.file_field :packet %>
    </div>

    <h2>Player Packets:</h2>
    <p>Use the box below to add a new character.  Just one at a time for now.  An empty box will not create a new character.</p>
    <% @game.characters.select {|c| c.id == nil}.each do |character| %>
      <%= form.fields_for :characters, character do |ff| %>
        <%= render "character_fields", ff: ff %>
      <% end %>
    <% end %>

    <p>Use the fields below to edit or delete existing characters:</p>
    <% @game.characters.select {|c| c.id != nil}.each do |character| %>
      <%= form.fields_for :characters, character do |ff| %>
        <p>
          <%= ff.label :name %>
          <%= ff.text_field :name %>
        </p>
        <p>
          <p>Current URL: <%= ff.object.player_packet %></p>
          <p><%= link_to("Download Current Player Packet", ff.object.player_packet.url) %></p>
          <%= ff.label :update_player_packet %>
          <%= ff.file_field :player_packet %>

          <% if ff.object.persisted? %>
            <%= ff.check_box :_destroy %>
            <%= ff.label :_destroy, "Destroy" %>
          <% end %>
        </p>
        <p>------------------------------------------------------------------</p>
      <% end %>
    <% end %>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
<div>
  <%= link_to "Back", game_path(@game), class: "w3-bar-item w3-button w3-left" %>
</div>

app/views/games/index.html.erb
<!-- Image header -->
<div class="w3-display-container w3-container">
  <%= image_tag "cowboy.jpg", alt:"Yippe Kayay!", style:"width:100%" %>
  <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
    <h2 class="w3-text-black w3-hide-small">Kill your friends, </h2>
    <h2 class="w3-text-black w3-hide-small">grab the loot.</h2>
    <h2 class="w3-hide-large w3-hide-medium" style="text-shadow: 0 0 3px #FF0000;">Kill your friends, </h2>
    <h2 class="w3-hide-large w3-hide-medium" style="text-shadow: 0 0 3px #FF0000;">grab the loot.</h2>
  </div>
</div>

<div>
  <p>Speakeasy Games sells immersive cocktail party games. Our games present tangled webs of backstories and conflicting interests that play out in a way that is entirely unique to each group of players. They are not classic "Murder Mysteries" because anybody can be the murderer-- or the victim. Each player comes to the game with different knowledge, a different perspective, and different goals. As each of them decides who to trust, who to betray, and who to callously manipulate for their own selfish ends, the larger shape of the plots will emerge. And, unlike your grandpa's immersive cocktail murder game extravaganzas, Speakeasy Games' plots can get very, very, weird. Each game can be played only once by the same group of people-- after that, the players will know too much.</p>
</div>

<!-- Product grid -->
<div class="w3-row w3-grayscale", style="display: table-row">
  <% @games.each do | game | %>
    <div class="w3-col l3 s6", style="display: table-cell; height:400px">
      <div class="w3-container">
        <% if game.cover_photo %>
          <%= image_tag(game.cover_photo.img.url(:medium), style:"width:100%", onerror: "this.style.display='none'") %>
        <% else %>
          <%= image_tag "cowboy.jpg", alt:"Yippe Kayay!", style:"width:100%" %>
        <% end %>
        <div class="w3-center">
          <br>
          <% if game.has_packet? %>
            <%= form_tag(orders_path) do %>
              <%= hidden_field_tag 'game_id', game.id %>
              <div><%= submit_tag 'Add to Cart' %></div>
            <% end %>
          <p><b><%= number_to_currency(game.price/100) %></b></p>
          <% else %>
            <p>COMING SOON!</p>
          <% end %>
          <p><%= link_to game.title, game_path(game) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div>
  <h1><%= @game.title %></h1>
  <p>An Immersive Cocktail Party Game for <%= @game.player_min %> to <%= @game.player_max %> Players</p>
  <% if @game.has_packet? %>
    <p>Price: <%= number_to_currency(@game.price/100) %></p>
    <%= form_tag(orders_path) do %>
      <%= hidden_field_tag 'game_id', @game.id %>
      <div><%= submit_tag 'Add to Cart' %></div>
    <% end %>
  <% else %>
    <p>COMING SOON!</p>
  <% end %>
  <h2>About the game:</h2>
  <p><%= @game.teaser %></p>
  <h2>What's Included: </h2>
  <p><%= @game.included %></p>
  <h2>What's Not Included: </h2>
  <p><%= @game.not_included %></p>
  <h2>Host Difficulty Level: </h2>
  <p><%= @game.difficulty %></p>
  <h2>Playing Time: </h2>
  <p><%= @game.play_time %> hours</p>
  <h2>Host Prep Time:</h2>
  <p>wildly variable, but at least <%= @game.prep_time %> hours</p>
  <h2>Host Notes: </h2>
  <p>Speakeasy Games are built around <span class="w3-text-green">players</span> with incomplete knowledge and a <span class="w3-text-red">host</span> (or hosts) with full knowledge of the plot, players' goals, and mysteries of the universe.  <b class="w3-text-black">Only read the host packet if you are planning on being the host.</b>  Host packets will be delivered by e-mail. When checking out, make sure you use an email address that the <b class="w3-text-black">host</b> has access to.</p>
  <p><%= @game.notes %></p>
  <% if @game.photos.count > 0 %>
    <h2>Photos</h2>
    <% @game.photos.each do |photo| %>
      <%= image_tag(photo.img.url(:medium), onerror: "this.style.display='none'") %>
    <% end %>
  <% end %>
  <% if @game.testimonials.count > 0 %>
    <h2>Testimonials</h2>
    <% @game.testimonials.each do |testimonial| %>
      <p><%= testimonial.description %></p>
    <% end %>
  <% end %>
</div>