config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' } #, confirmations: 'confirmations' }
  resources :users
  root to: "games#index"
  resources :games, only: [:index, :show, :new, :edit, :update, :destroy] do
    resources :characters
  end
  resources :photos, only: [:destroy]
  resources :cover_photos, only: [:destroy]
  resources :testimonials, only: [:destroy]
  resources :charges
  resources :orders
  resources :countdowns, only: [:create, :show, :index]
  get 'countdowns/:id/search' => 'countdowns#search', as: "search_path"
  get 'countdowns/:id/ending' => 'countdowns#ending', as: "ending_path"
  post 'games/:game_id/characters/invite' => 'characters#invite', as: "invite_path"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speakeasy Games</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .w3-sidebar a {font-family: "Roboto", sans-serif}
      body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
  </head>

  <body class="w3-content" style="max-width:1200px">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-black w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
      <div class="w3-container w3-display-container w3-padding-16">
        <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
        <h3 class="w3-wide"><b><%= link_to "", root_path, class: "w3-button LOGO" %></b></h3>
      </div>
      <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
        <%= link_to "How Does This Work?", orders_path, class: "w3-bar-item w3-button w3-text-light-blue" %>
        <% if @games %>

          <% if @games.active.count > 0 %>
            <p class="w3-container w3-small w3-text-blue">Ready to Play:</p>
            <% @games.active.each do | game | %>
              <%= link_to game.title, game_path(game), class: "w3-bar-item w3-button w3-text-blue" %>
            <% end %>
          <% end %>

          <% if @games.coming_soon.count > 0 %>
            <p class="w3-container w3-small">Coming Soon:</p>
            <% @games.coming_soon.each do | game | %>
              <%= link_to game.title, game_path(game), class: "w3-button w3-bar-item w3-medium w3-text-grey" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <% if current_user %>
        <%= link_to "My Account", user_path(current_user), class: "w3-bar-item w3-button w3-left"%>
        <% if current_user.admin? && @game %>
          <%= link_to "Edit", edit_game_path(@game), class: "w3-bar-item w3-button w3-left" %>
        <% end %>
        <%= link_to "Logout", destroy_user_session_path, method: "DELETE", class: "w3-bar-item w3-button w3-right" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "w3-bar-item w3-button" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "w3-bar-item w3-button" %>
      <% end %>
      <%= link_to "Home", root_path, class: "w3-bar-item w3-button w3-left" %>
      <a href="#footer" class="w3-bar-item w3-button w3-padding">Contact Us</a>
    </nav>

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-hide-large w3-black w3-xlarge">
      <div class="w3-padding-24 w3-wide w3-center"><h1><%= link_to "Speakeasy", root_path, class: "w3-button" %><%= link_to "Games", root_path, class: "w3-button" %></h1></div>
      <p class="w3-right">
        <% if current_user && current_user.orders.where(complete: false).count > 0 %>
          <%= link_to "", order_path(current_user.orders.where(complete: false)[0]), class:"fa fa-shopping-cart w3-margin-right w3-button" %>
        <% elsif current_user %>
          <%= link_to "", "", class:"fa fa-shopping-cart w3-margin-right w3-button" %>
        <% else %>
          <%= link_to "", new_user_session_path, class:"fa fa-shopping-cart w3-margin-right w3-button" %>
        <% end %>
      </p>
      <%= link_to "", root_path, class: "w3-button w3-padding-24 LOGO" %>
      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

      <!-- Push down content on small screens -->
      <div class="w3-hide" style="margin-top:123px"></div>

      <!-- Top header -->
      <header class="w3-container w3-xlarge w3-black w3-hide-small w3-hide-medium">
        <h1 class="w3-left"><%= link_to "Speakeasy Games", root_path, class: "w3-button" %></h1>
        <p class="w3-right">
          <% if current_user && current_user.orders.where(complete: false).count > 0 %>
            <%= link_to "", order_path(current_user.orders.where(complete: false)[0]), class:"fa fa-shopping-cart w3-margin-right w3-button" %>
          <% elsif current_user %>
            <%= link_to "", "", class:"fa fa-shopping-cart w3-margin-right w3-button", style:"text-decoration: none", onclick: "alert('Your cart is empty.')" %>
          <% else %>
            <%= link_to "", new_user_session_path, class:"fa fa-shopping-cart w3-margin-right w3-button", style:"text-decoration: none", onclick: "alert('Please log in to add items to your cart.')" %>
          <% end %>
        </p>
      </header>

      <div class="w3-container w3-text-grey" id="jeans">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p class="w3-text-red"><%= flash[:error] %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>

      <!-- Footer -->
      <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
        <div class="w3-row-padding w3-center">
          <h1>Contact Us!</h1>
          <div class="w3-col">
            <h4>Questions? Comments?  Suggestions?</h4>
            <p>We want to hear from you!  Send us an email or find us on one of the social media channels below.</p>
            <div class="w3-col">
              <%= link_to "", "https://www.facebook.com/Speakeasy-Games/", class:"fa fa-facebook-official w3-hover-opacity w3-large w3-button" %>
              <%= link_to "", "https://www.instagram.com/speakeasy_games/", class:"fa fa-instagram w3-hover-opacity w3-large w3-button" %>
              <%= link_to "", "https://www.twitter.com/speakeasy_games/", class:"fa fa-twitter w3-hover-opacity w3-large w3-button" %>
              <%= link_to "", "mailto:playspeakeasygames@gmail.com", class:"fa fa-envelope w3-hover-opacity w3-large w3-button" %>

            </div>
          </div>

        </div>
      </footer>

      <div class="w3-black w3-center w3-padding-24">
        <p>Website by Gilad Shanan</p>
        <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p>
      </div>

      <!-- End page content -->
    </div>

    <script>
    // Script to open and close sidebar
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("myOverlay").style.display = "block";
    }

    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("myOverlay").style.display = "none";
    }
    </script>

  </body>
</html>